
import { Beneficiary } from './types';

export const BENEFICIARY_DATA: Beneficiary[] = [
  {
    id: 1,
    state: "UTTAR PRADESH",
    district: "Agra",
    block: "Akola",
    gramPanchayat: "SIROALI",
    village: "SIRAULI",
    shgCode: "31008265621",
    shgName: "JAY BHEEM SHG",
    dateOfFormation: "19-06-2019",
    memberCode: "310090690433",
    memberName: "RAJANI DEVI",
    dateOfBirth: "01-01-1989",
    dateOfJoiningInSHG: "19-06-2019",
    designationInSHG: "MEMBER",
    socialCategory: "SC",
    pvtg: "No",
    religion: "HINDU",
    education: "ILLITERATE",
    gender: "FEMALE",
    maritalStatus: "MARRIED",
    insurance: "No",
    disability: "No Disability",
    disabilityType: "",
    isHeadOfFamily: "YES",
    fatherMotherSpouseName: "DINDAYAL SINGH",
    relation: "SPOUSE",
    accountNumber: "XXXXXXXX4070",
    ifsc: "CNRB0001524",
    branchName: "ARUA KATARA",
    bankName: "CANARA BANK",
    accountOpeningDate: "27-08-2014",
    accountType: "SAVINGS",
    mobileNo: "XXXXXX1237",
    aadhaarKYC: "VERIFIED",
    eKYC: "No",
    cadres: "",
    primaryLivelihoods: "Agriculture Activities",
    secondaryLivelihoods: "Livestock Rearing-Goat",
    tertiaryLivelihoods: "",
    nregaJobCardNumber: "",
    pmaygId: "",
    seccTin: "",
    nrlmMisId: "3651391",
    stateMisId: "UP_OMSHANTIS",
    ebkId: "KRISHNA",
    ebkName: "81...",
    bkMobileNo: "273611476",
    approvalStatus: "Pending with Bookkeeper",
    firstTimeApprovalDate: "26-04-2023",
    status: 'ACTIVE',
    inactiveRejectDate: "",
    inactiveRejectReason: "",
    migratedLokos: "Migrated Member",
  },
  {
    id: 2,
    state: "UTTAR PRADESH",
    district: "Agra",
    block: "Akola",
    gramPanchayat: "SIROALI",
    village: "SIRAULI",
    shgCode: "31008265621",
    shgName: "JAY BHEEM SHG",
    dateOfFormation: "19-06-2019",
    memberCode: "310090690357",
    memberName: "BHAGWATI DEVI",
    dateOfBirth: "01-01-1983",
    dateOfJoiningInSHG: "19-06-2019",
    designationInSHG: "MEMBER",
    socialCategory: "OBC",
    pvtg: "No",
    religion: "HINDU",
    education: "CLASS - 8",
    gender: "FEMALE",
    maritalStatus: "MARRIED",
    insurance: "No",
    disability: "No Disability",
    disabilityType: "",
    isHeadOfFamily: "YES",
    fatherMotherSpouseName: "RAM KISHAN",
    relation: "SPOUSE",
    accountNumber: "XXXXXXXX3484",
    ifsc: "UBIN0540218",
    branchName: "MALPURA",
    bankName: "UNION BANK OF INDIA",
    accountOpeningDate: "17-12-2016",
    accountType: "SAVINGS",
    mobileNo: "XXXXXX4147",
    aadhaarKYC: "VERIFIED",
    eKYC: "No",
    cadres: "",
    primaryLivelihoods: "Agriculture Activities",
    secondaryLivelihoods: "Livestock Rearing-Goat",
    tertiaryLivelihoods: "",
    nregaJobCardNumber: "UP-20-003-032-002/193",
    pmaygId: "UP134728859",
    seccTin: "",
    nrlmMisId: "3651405",
    stateMisId: "UP_OMSHANTIS",
    ebkId: "KRISHNA",
    ebkName: "81...",
    bkMobileNo: "273611476",
    approvalStatus: "Inactive By Bookkeeper",
    firstTimeApprovalDate: "26-04-2023",
    status: 'INACTIVE',
    inactiveRejectDate: "02-06-2025",
    inactiveRejectReason: "Member left the group voluntarily",
    migratedLokos: "Migrated Member",
  },
  {
    id: 3,
    state: "UTTAR PRADESH",
    district: "Agra",
    block: "Akola",
    gramPanchayat: "SIROALI",
    village: "SIRAULI",
    shgCode: "31008265785",
    shgName: "SANT RAVIDAS SHG",
    dateOfFormation: "02-04-2021",
    memberCode: "310118463332",
    memberName: "KANTA DEVI",
    dateOfBirth: "01-01-1978",
    dateOfJoiningInSHG: "02-04-2021",
    designationInSHG: "MEMBER",
    socialCategory: "SC",
    pvtg: "No",
    religion: "HINDU",
    education: "CLASS - 5",
    gender: "FEMALE",
    maritalStatus: "MARRIED",
    insurance: "No",
    disability: "No Disability",
    disabilityType: "",
    isHeadOfFamily: "NO",
    fatherMotherSpouseName: "GHANSHYAM",
    relation: "SPOUSE",
    accountNumber: "",
    ifsc: "",
    branchName: "",
    bankName: "",
    accountOpeningDate: "",
    accountType: "",
    mobileNo: "XXXXXX8405",
    aadhaarKYC: "VERIFIED",
    eKYC: "No",
    cadres: "",
    primaryLivelihoods: "Daily Wages-Others",
    secondaryLivelihoods: "Livestock Rearing-Goat",
    tertiaryLivelihoods: "",
    nregaJobCardNumber: "",
    pmaygId: "",
    seccTin: "",
    nrlmMisId: "6812513",
    stateMisId: "UP_NAVIYOTI",
    ebkId: "SAPNA",
    ebkName: "74...",
    bkMobileNo: "409414040",
    approvalStatus: "Approved by BM",
    firstTimeApprovalDate: "26-04-2023",
    status: 'ACTIVE',
    inactiveRejectDate: "",
    inactiveRejectReason: "",
    migratedLokos: "Migrated Member",
  },
  {
    id: 4,
    state: "UTTAR PRADESH",
    district: "Agra",
    block: "Barauli Ahir",
    gramPanchayat: "NAGLA",
    village: "NAGLA",
    shgCode: "31008265999",
    shgName: "ROSHNI SHG",
    dateOfFormation: "10-01-2022",
    memberCode: "310118464000",
    memberName: "GEETA",
    dateOfBirth: "10-02-1995",
    dateOfJoiningInSHG: "10-01-2022",
    designationInSHG: "PRESIDENT",
    socialCategory: "GENERAL",
    pvtg: "No",
    religion: "HINDU",
    education: "GRADUATE",
    gender: "FEMALE",
    maritalStatus: "MARRIED",
    insurance: "Yes",
    disability: "No Disability",
    disabilityType: "",
    isHeadOfFamily: "YES",
    fatherMotherSpouseName: "RAKESH KUMAR",
    relation: "SPOUSE",
    accountNumber: "XXXXXXXX7777",
    ifsc: "PUNB012345",
    branchName: "AGRA CANTT",
    bankName: "PUNJAB NATIONAL BANK",
    accountOpeningDate: "11-01-2022",
    accountType: "SAVINGS",
    mobileNo: "XXXXXX9999",
    aadhaarKYC: "VERIFIED",
    eKYC: "Yes",
    cadres: "BC Sakhi",
    primaryLivelihoods: "Small Business",
    secondaryLivelihoods: "",
    tertiaryLivelihoods: "",
    nregaJobCardNumber: "",
    pmaygId: "",
    seccTin: "",
    nrlmMisId: "6812514",
    stateMisId: "UP_ROSHNI",
    ebkId: "GEETA",
    ebkName: "91...",
    bkMobileNo: "409414041",
    approvalStatus: "Approved by BM",
    firstTimeApprovalDate: "28-01-2022",
    status: 'ACTIVE',
    inactiveRejectDate: "",
    inactiveRejectReason: "",
    migratedLokos: "Migrated Member",
  },
  {
    id: 5,
    state: "UTTAR PRADESH",
    district: "Firozabad",
    block: "Tundla",
    gramPanchayat: "RAMPUR",
    village: "RAMPUR",
    shgCode: "31009999888",
    shgName: "UJJALA SHG",
    dateOfFormation: "25-05-2018",
    memberCode: "310207040222",
    memberName: "SANGEETA",
    dateOfBirth: "15-08-1990",
    dateOfJoiningInSHG: "25-05-2018",
    designationInSHG: "SECRETARY",
    socialCategory: "OBC",
    pvtg: "No",
    religion: "HINDU",
    education: "CLASS - 12",
    gender: "FEMALE",
    maritalStatus: "MARRIED",
    insurance: "No",
    disability: "No Disability",
    disabilityType: "",
    isHeadOfFamily: "NO",
    fatherMotherSpouseName: "ANIL KUMAR",
    relation: "SPOUSE",
    accountNumber: "XXXXXXXX5555",
    ifsc: "SBIN0001234",
    branchName: "TUNDLA",
    bankName: "STATE BANK OF INDIA",
    accountOpeningDate: "01-06-2018",
    accountType: "SAVINGS",
    mobileNo: "XXXXXX8888",
    aadhaarKYC: "VERIFIED",
    eKYC: "No",
    cadres: "",
    primaryLivelihoods: "Agriculture Activities",
    secondaryLivelihoods: "Tailoring",
    tertiaryLivelihoods: "",
    nregaJobCardNumber: "",
    pmaygId: "UP567890123",
    seccTin: "",
    nrlmMisId: "7712515",
    stateMisId: "UP_UJJALA",
    ebkId: "SANGEETA",
    ebkName: "92...",
    bkMobileNo: "501234567",
    approvalStatus: "Rejected by BM",
    firstTimeApprovalDate: "26-04-2023",
    status: 'INACTIVE',
    inactiveRejectDate: "29-08-2025",
    inactiveRejectReason: "No bank",
    migratedLokos: "Migrated Member",
  }
];
